name: lint-and-prettier-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: "20.11.1"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm run lint

  prettier:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npx prettier --check .

  typecheck:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm run typecheck